In [1]:
import pandas as pd 
import numpy as np

In [3]:
data=pd.read_csv("C:/Users/HP/OneDrive/Desktop/population data/mckinsey.csv")
print(data.head())

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [14]:
#data cleaning
data.info()
type(data)

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   str
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   str
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 103.7 KB

pandas.DataFrame

In [5]:
data.describe()

             year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [9]:
total_population = data['population'].sum()
print("Total Population:", total_population)

Total Population: 50440465801

In [11]:
#which country has highest population   
highest_population_country = data.loc[data['population'].idxmax(), 'country']  
print("Country with Highest Population:", highest_population_country)

Country with Highest Population: China

In [13]:
#which country has the lowest population
lowest_population= data.loc[data['population'].idxmin(),'country']
print("Country with lowest population: ",lowest_population)

Country with lowest population:  Sao Tome and Principe

In [ ]:
#create a new coloumn
data['population_in_millions'] = data['population'] / 1_000_000
print(data[['country', 'population_in_millions']])

In [ ]:
data.columns
data["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: str

In [17]:
type(data["country"])

pandas.Series

In [ ]:
#change life_exp into the string
data['life_exp'] = data['life_exp'].astype(str)

In [23]:
data[['country']].head()

       country
0  Afghanistan
1  Afghanistan
2  Afghanistan
3  Afghanistan
4  Afghanistan

In [24]:
data['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [25]:
data.rename(columns={"country":"Country"})

          Country  year  population continent life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia   28.801  779.445314
1     Afghanistan  1957     9240934      Asia   30.332  820.853030
2     Afghanistan  1962    10267083      Asia   31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.02  836.197138
4     Afghanistan  1972    13079460      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987     9216418    Africa   62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa   60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa   46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa   39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa   43.487  469.709298

[1704 rows x 6 columns]